package com.fxbrief.report.service;

import com.fxbrief.analysis.dto.PairAnalysis;
import com.fxbrief.analysis.dto.ReportPayload;
import com.fxbrief.analysis.dto.SignalState;
import org.springframework.stereotype.Component;

/**
 * Fallback composer for the report-level summary stored on
 * {@code market_analysis.summary} and copied verbatim onto every
 * {@code user_reports.summary} that references the same analysis row.
 *
 * <h2>Primary source is Claude</h2>
 * Per PRD §8.4, the report summary is generated by Claude as part of the
 * mega-call response (see {@link com.fxbrief.analysis.service.MegaCallNarrativeService}).
 * This composer runs <b>only when</b> the mega-call's summary is missing,
 * blank, exceeds the 100-character cap, or the entire mega-call path
 * fell through to per-pair fallback (which has no report-level summary).
 *
 * See DECISIONS D-051 for the history of this design: the original D-050
 * had this composer as the primary source; D-051 reversed that after the
 * PRD was updated to specify Claude as the source.
 *
 * <h2>Output examples</h2>
 * Two PRD examples it must reproduce verbatim when conditions match:
 * <ul>
 *   <li>{@code "3 setups available — GBP/USD best opportunity"}</li>
 *   <li>{@code "Markets consolidating — no clear setups"}</li>
 * </ul>
 *
 * Hard cap at 100 characters to match the column length constraint.
 */
@Component
public class ReportSummaryComposer {

    static final int MAX_LENGTH = 100;

    public String compose(ReportPayload payload) {
        if (payload == null) {
            return "Report unavailable";
        }
        if (payload.marketsConsolidating()) {
            return clamp("Markets consolidating — no clear setups");
        }

        int validSetups = 0;
        if (payload.pairs() != null) {
            for (PairAnalysis p : payload.pairs()) {
                if (isValidSetup(p)) {
                    validSetups++;
                }
            }
        }

        String bestPair = payload.bestPair();
        if (validSetups == 0) {
            if (bestPair != null && !bestPair.isBlank()) {
                return clamp(bestPair + " best opportunity — no confirmed setups");
            }
            return clamp("No confirmed setups today");
        }

        StringBuilder sb = new StringBuilder();
        sb.append(validSetups).append(validSetups == 1 ? " setup available" : " setups available");
        if (bestPair != null && !bestPair.isBlank()) {
            sb.append(" — ").append(bestPair).append(" best opportunity");
        }
        return clamp(sb.toString());
    }

    private boolean isValidSetup(PairAnalysis p) {
        if (p == null || p.signalState() == null) {
            return false;
        }
        SignalState state = p.signalState();
        return state == SignalState.CONFIRMED || state == SignalState.AWAITING_CONFIRMATION;
    }

    private String clamp(String s) {
        if (s.length() <= MAX_LENGTH) {
            return s;
        }
        return s.substring(0, MAX_LENGTH);
    }
}
